### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by abruzzihraig** [syntax-tree/hastscript#4]
Hi, I just noticed there is a camel case issue in SVG. The property 'viewBox' will be parsed as 'view-box' in the produced HTML.

e.g. 
Input
```
h('svg', {
    fill: '#000000',
    height: 24,
    width: 24,
    viewBox: '0 0 24 24',
    xmlns: 'http://www.w3.org/2000/svg',
    class: 'carousel-prev-step'
}
```
Output
```
<svg fill="#000000" height="24" width="24" view-box="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="carousel-prev-step"><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path d="M0 0h24v24H0z" fill="none"></path></svg>
```

The expected result should be `<svg viewBox="0 0 24 24">`

**Comment by wooorm** [comment]
Hey @abruzzihraig!

Sorry for the delay!

I thought about it a bit and I’d like to work on this now. For starters, this issue is now first tracked in https://github.com/wooorm/property-information/issues/6. When that is done, we can work on updating it throughout the ecosystem.

I’ll close this now, if you have any further comments please post them there!
